### ISSUE TITLE
Mez not breaking on attack

### ISSUE THREAD

**Issue by Kekrons** [mixxit/solinia3-core#294] opened 2019-01-01 12:41 UTC
[Meztest.zip](https://github.com/mixxit/solinia3-core/files/2719313/Meztest.zip)

**Comment by mixxit** [comment] 2019-01-11 13:21
closing, if this is still an issue please reopen

**Comment by Ferreluke** [comment] 2019-01-11 18:41
This is definitely still an issue

**Comment by Ferreluke** [comment] 2019-01-11 18:44
A target under the effects of mesmerization will remain stunned even after receiving damage. All mez spells are supposed to break when a mez'd target receives damage. At the moment, mez is in an extremely over-powered stun that's irresistible in most cases.

**Comment by mixxit** [comment] 2019-01-16 21:33
So this does actually break on attack and was confirmed
It was also confirmed as resisting (depending on the mez spell resist type)

However there wasnt an instant drop of mez, it would drop at the end of the current tick

We have adjusted this slightly

You will also with bard spells, since they constantly apply, have the instant drop and chance to hit back bnefore the next pulse kicks in

Fixed and operating as it did on EQ

**Closed by mixxit** 2019-01-16 21:33 UTC
Labels: Caster issue, bug
