### ISSUE TITLE
Pet doesn't do damage

### ISSUE THREAD

**Issue by Fran9676** [mixxit/solinia3-core#179] opened 2018-06-23 14:17 UTC
I'm trying the enchanter class and I found that the pet of this class doesn't do damage to mobs

**Comment by mixxit** [comment] 2018-06-23 14:50
This is affecting all pets, thank for reporting this

**Comment by mixxit** [comment] 2018-06-23 14:52
This is caused by pets having no weapon

**Comment by mixxit** [comment] 2018-06-23 14:56
Resolved in 06458ab

**Closed by mixxit** 2018-06-23 14:56 UTC

**Comment by Fran9676** [comment] 2018-06-23 15:30
it's still bugged

**Comment by mixxit** [comment] 2018-06-23 15:30
Which pet

**Comment by Fran9676** [comment] 2018-06-23 15:33
the pet orb doesn't work for my pet

**Comment by mixxit** [comment] 2018-06-23 15:59
Separate ticket was opened for this
